import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.scss'
import { client } from "../graphql/ApolloClient";
import {getCharacters} from '../graphql/queries'

import Card from '../component/card/card'

export interface CharacterDetails {
  id: string;
  name: string;
  status: string;
  gender: string;
  image: string
}
interface Info {
  count: number;
  pages: number;
  next: number;
  prev: number
}
interface CharactersData {
  info: Info;
  results: CharacterDetails[]
}

interface PageProps {
  characters: CharactersData;
  loading: boolean
}


const Home:React.FC<PageProps>= ({ characters, loading }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.pageHeader}>Rick and Morty Characters</div>
        <div className={styles.characterList}>
          {
            loading ? (<div>Loading...</div>) : characters.results.map((char:CharacterDetails)=>{
              return (<Card char={char} />)
            })
          }
        </div>
      </main>

    </div>
  )
}

export const getStaticProps = async () => {
  const { data, loading } = await client.query({
    query: getCharacters,
  });

  return {
    props: {
      characters: data.characters,
      loading,
    },
  };
};

export default Home
